config/routes.rb
Rails.application.routes.draw do
  resources :favourites
  resources :television_shows
  resources :movies
  resources :animes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to:'favourites#index'


end

app/models/television_show.rb
class TelevisionShow < ApplicationRecord
		validates :name, :details, presence: true

end

app/controllers/television_shows_controller.rb
class TelevisionShowsController < ApplicationController
  before_action :set_television_show, only: [:show, :edit, :update, :destroy]

  # GET /television_shows
  # GET /television_shows.json
  def index
    @television_shows = TelevisionShow.all
  end

  # GET /television_shows/1
  # GET /television_shows/1.json
  def show
  end

  # GET /television_shows/new
  def new
    @television_show = TelevisionShow.new
  end

  # GET /television_shows/1/edit
  def edit
  end

  # POST /television_shows
  # POST /television_shows.json
  def create
    @television_show = TelevisionShow.new(television_show_params)

    respond_to do |format|
      if @television_show.save
        format.html { redirect_to @television_show, notice: 'Television show was successfully created.' }
        format.json { render :show, status: :created, location: @television_show }
      else
        format.html { render :new }
        format.json { render json: @television_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /television_shows/1
  # PATCH/PUT /television_shows/1.json
  def update
    respond_to do |format|
      if @television_show.update(television_show_params)
        format.html { redirect_to @television_show, notice: 'Television show was successfully updated.' }
        format.json { render :show, status: :ok, location: @television_show }
      else
        format.html { render :edit }
        format.json { render json: @television_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /television_shows/1
  # DELETE /television_shows/1.json
  def destroy
    @television_show.destroy
    respond_to do |format|
      format.html { redirect_to television_shows_url, notice: 'Television show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_television_show
      @television_show = TelevisionShow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def television_show_params
      params.require(:television_show).permit(:name, :details)
    end
end

app/helpers/television_shows_helper.rb
module TelevisionShowsHelper
end

app/views/television_shows/_form.html.erb
<%= form_for(television_show) do |f| %>
  <% if television_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(television_show.errors.count, "error") %> prohibited this television_show from being saved:</h2>

      <ul>
      <% television_show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :details %>
    <%= f.text_area :details %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/television_shows/edit.html.erb
<h1>Editing Television Show</h1>

<%= render 'form', television_show: @television_show %>

<%= link_to 'Show', @television_show %> |
<%= link_to 'Back', television_shows_path %>

app/views/television_shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Television Shows</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @television_shows.each do |television_show| %>
      <tr>
        <td><%= television_show.name %></td>
        <td><%= television_show.details %></td>
        <td><%= link_to 'Show', television_show %></td>
        <td><%= link_to 'Edit', edit_television_show_path(television_show) %></td>
        <td><%= link_to 'Destroy', television_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Television Show', new_television_show_path %><br>
<%= link_to 'To Anime', animes_path %><br>
<%= link_to 'To Movie', movies_path %><br>
<%= link_to 'Back to Favourites', favourites_path %>

app/views/television_shows/new.html.erb
<h1>New Television Show</h1>

<%= render 'form', television_show: @television_show %>

<%= link_to 'Back', television_shows_path %>

app/views/television_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @television_show.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @television_show.details %>
</p>

<%= link_to 'Edit', edit_television_show_path(@television_show) %> |
<%= link_to 'Back', television_shows_path %>