config/routes.rb
Rails.application.routes.draw do
  resources :favourites
  resources :television_shows
  resources :movies
  resources :animes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to:'favourites#index'


end

app/models/favourite.rb
class Favourite < ApplicationRecord
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :set_favourite, only: [:show, :edit, :update, :destroy]

  # GET /favourites
  # GET /favourites.json
  def index
    @favourites = Favourite.all
  end

  # GET /favourites/1
  # GET /favourites/1.json
  def show
  end

  # GET /favourites/new
  def new
    @favourite = Favourite.new
  end

  # GET /favourites/1/edit
  def edit
  end

  # POST /favourites
  # POST /favourites.json
  def create
    @favourite = Favourite.new(favourite_params)

    respond_to do |format|
      if @favourite.save
        format.html { redirect_to @favourite, notice: 'Favourite was successfully created.' }
        format.json { render :show, status: :created, location: @favourite }
      else
        format.html { render :new }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourites/1
  # PATCH/PUT /favourites/1.json
  def update
    respond_to do |format|
      if @favourite.update(favourite_params)
        format.html { redirect_to @favourite, notice: 'Favourite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favourite }
      else
        format.html { render :edit }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    @favourite.destroy
    respond_to do |format|
      format.html { redirect_to favourites_url, notice: 'Favourite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favourite_params
      params.require(:favourite).permit(:anime, :movie, :television_show)
    end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_form.html.erb
<%= form_for(favourite) do |f| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% favourite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :anime %>
    <%= f.text_area :anime %>
  </div>

  <div class="field">
    <%= f.label :movie %>
    <%= f.text_area :movie %>
  </div>

  <div class="field">
    <%= f.label :television_show %>
    <%= f.text_area :television_show %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favourites</h1>

<table>
 
     
      <tr><%= link_to 'Anime', animes_path %>
</th><br>
      <tr><%= link_to 'Movie', movies_path %>
</th><br>
      <tr><%= link_to 'TelevisionShow', television_shows_path %>
</th><br>
      <tr colspan="3"> 
 

</table>

<br>
 

app/views/favourites/new.html.erb
<h1>New Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Anime:</strong>
  <%= @favourite.anime %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @favourite.movie %>
</p>

<p>
  <strong>Television show:</strong>
  <%= @favourite.television_show %>
</p>

<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>